# Generated by Django 5.1.3 on 2024-12-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='accessoriesCategroy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='accessories.accesscategroy'),
        ),
    ]
