# Generated by Django 5.1.3 on 2024-12-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(default='unknown', max_length=9),
        ),
    ]
