# Generated by Django 5.1.3 on 2025-04-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
