# Generated by Django 5.1.3 on 2024-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritions',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
