# Generated by Django 5.1.3 on 2024-11-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0002_nutritions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritions',
            name='type',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('accessory', 'Accessory')], default='nutrition', max_length=10),
        ),
    ]
