# Generated by Django 5.1.3 on 2024-12-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0002_brand_date_added_category_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritions',
            old_name='goal',
            new_name='goals',
        ),
    ]
