# Generated by Django 5.1.3 on 2024-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0003_rename_goal_nutritions_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritions',
            old_name='goals',
            new_name='goal',
        ),
    ]
