# Generated by Django 5.1.3 on 2024-11-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0004_brand_category_goals_remove_nutritions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritions',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritions', to='nutritions.brand'),
        ),
        migrations.AddField(
            model_name='nutritions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritions', to='nutritions.category'),
        ),
        migrations.AddField(
            model_name='nutritions',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritions', to='nutritions.goals'),
        ),
    ]
