# Generated by Django 5.1.3 on 2024-11-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0005_nutritions_brand_nutritions_category_nutritions_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritions',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
