# Generated by Django 5.1.3 on 2024-11-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0006_brand_image_category_image_goals_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='goals',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
    ]
