# Generated by Django 5.1.3 on 2024-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0008_nutritions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritions',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
